/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor da8409a-dirty+da8409a60d4fcb997a85ffd2c672744b7f600cec

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0xFFFFFFFF,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1008_manufacturerDeviceName = {'-', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x100A_manufacturerSoftwareVersion = {'-', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x1012_COB_IDTimeStampObject = 0x80000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x1388,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x50555341,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000200,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000300,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000400,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000500,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1404_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000000,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1405_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000000,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1406_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000000,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1601_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1602_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1603_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1604_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1605_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1606_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0xA4C00108,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x2710,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x2710,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000380,
        .transmissionType = 0xFE,
        .inhibitTime = 0x2710,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000480,
        .transmissionType = 0xFE,
        .inhibitTime = 0x2710,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x60000108,
        .applicationObject2 = 0x60000208,
        .applicationObject3 = 0x60000308,
        .applicationObject4 = 0x60000408,
        .applicationObject5 = 0xA0400108,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x64010110,
        .applicationObject2 = 0x64010210,
        .applicationObject3 = 0x64010310,
        .applicationObject4 = 0x64010410,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A02_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x64010510,
        .applicationObject2 = 0x64010610,
        .applicationObject3 = 0x64010710,
        .applicationObject4 = 0x64010810,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A03_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x64020120,
        .applicationObject2 = 0x64020220,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x2101_nodeID = 0x7E,
    .x2102_bitrate = 0x00FA,
    .x2300_schedulerActivates_sub0 = 0x08,
    .x2300_schedulerActivates = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x2301_schedulerOutputValue_sub0 = 0x08,
    .x2301_schedulerOutputValue = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x2302_schedulerOutputAddress_sub0 = 0x08,
    .x2302_schedulerOutputAddress = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x2303_schedulerTime_sub0 = 0x08,
    .x2303_schedulerTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x2304_schedulerTimeHour_sub0 = 0x08,
    .x2304_schedulerTimeHour = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x2305_schedulerTimeMinute_sub0 = 0x08,
    .x2305_schedulerTimeMinute = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x4002_debounceFilterMask8Bit_sub0 = 0x08,
    .x4002_debounceFilterMask8Bit = {0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x4003_debounceTime = 0x14,
    .x4004_AC_FilterMask8Bit_sub0 = 0x08,
    .x4004_AC_FilterMask8Bit = {0x00, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x4005_AC_Time = 0x0032,
    .x4201_outputPeriod_sub0 = 0x08,
    .x4201_outputPeriod = {0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000},
    .x4203_outputImpulseTime_sub0 = 0x08,
    .x4203_outputImpulseTime = {0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000},
    .x4401_processAnalogueInput_sub0 = 0x10,
    .x4401_processAnalogueInput = {0x00000355, 0x00000355, 0x00000355, 0x00000355, 0x00000355, 0x00000355, 0x00000355, 0x00000355, 0x00000101, 0x00000101, 0x00000101, 0x00000101, 0x00000101, 0x00000101, 0x00000101, 0x00000101},
    .x4402_multiplierAnalogueInput_sub0 = 0x10,
    .x4402_multiplierAnalogueInput = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    .x4403_dividerAnalogueInput_sub0 = 0x10,
    .x4403_dividerAnalogueInput = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    .x4501_WM_Setting_sub0 = 0x04,
    .x4501_WM_Setting = {0, 0, 0, 0},
    .x4502_WM_AngleStart_sub0 = 0x10,
    .x4502_WM_AngleStart = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x4503_WM_AngleStop_sub0 = 0x10,
    .x4503_WM_AngleStop = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x4504_WM_Speed_sub0 = 0x10,
    .x4504_WM_Speed = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x4510_userSettings_sub0 = 0x10,
    .x4510_userSettings = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5204_outputDuty_sub0 = 0x08,
    .x5204_outputDuty = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5205_outputImpilse_sub0 = 0x08,
    .x5205_outputImpilse = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5301_outputMask_sub0 = 0x08,
    .x5301_outputMask = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5302_inputRegisterAddresses_sub0 = 0x08,
    .x5302_inputRegisterAddresses = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5303_inputValueMasks_sub0 = 0x08,
    .x5303_inputValueMasks = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5304_inputValuePolarity_sub0 = 0x08,
    .x5304_inputValuePolarity = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5401_inputRegisterAddresses_sub0 = 0x18,
    .x5401_inputRegisterAddresses = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5402_inputRegisterMasks_sub0 = 0x18,
    .x5402_inputRegisterMasks = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5403_inputRegisterPolarity_sub0 = 0x18,
    .x5403_inputRegisterPolarity = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5404_outputRegisterAddresses_sub0 = 0x18,
    .x5404_outputRegisterAddresses = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5405_outputValues_sub0 = 0x18,
    .x5405_outputValues = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x5406_ruleMode_sub0 = 0x18,
    .x5406_ruleMode = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x6002_polarityInput8Bit_sub0 = 0x08,
    .x6002_polarityInput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6003_filterConstantInput8Bit_sub0 = 0x08,
    .x6003_filterConstantInput8Bit = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF},
    .x6005_globalInterruptEnable = true,
    .x6006_interruptMaskAnyChange8Bit_sub0 = 0x08,
    .x6006_interruptMaskAnyChange8Bit = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF},
    .x6007_interruptMaskLowToHigh8Bit_sub0 = 0x08,
    .x6007_interruptMaskLowToHigh8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6008_interruptMaskHighToLow8Bit_sub0 = 0x08,
    .x6008_interruptMaskHighToLow8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6202_polarityOutput8Bit_sub0 = 0x08,
    .x6202_polarityOutput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6208_filterMaskOutput8Bit_sub0 = 0x08,
    .x6208_filterMaskOutput8Bit = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF},
    .x6421_interruptTriggerSelection_sub0 = 0x08,
    .x6421_interruptTriggerSelection = {0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07},
    .x6423_analogInputGlobalInterruptEnable = true,
    .x6424_analogInputUpperLimit_sub0 = 0x10,
    .x6424_analogInputUpperLimit = {-2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648, -2147483648},
    .x6425_analogInputLowerLimit_sub0 = 0x10,
    .x6425_analogInputLowerLimit = {2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647},
    .x6426_analogInputDelta_sub0 = 0x10,
    .x6426_analogInputDelta = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6427_analogInputDeltaNegative_sub0 = 0x10,
    .x6427_analogInputDeltaNegative = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6428_analogInputDeltaPositive_sub0 = 0x10,
    .x6428_analogInputDeltaPositive = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6429_analogInputTriggers_sub0 = 0x04,
    .x6429_analogInputTriggers = {0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x6431_analogInputCompensate_sub0 = 0x10,
    .x6431_analogInputCompensate = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6443_analogueOutputErrorMode_sub0 = 0x08,
    .x6443_analogueOutputErrorMode = {0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01}
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x4500_LCD = 0x0000,
    .x5000_interrupt8bit_sub0 = 0x08,
    .x5000_interrupt8bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5006_interruptAnyChange8Bitt_sub0 = 0x08,
    .x5006_interruptAnyChange8Bitt = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5007_interruptLowToHigh8Bit_sub0 = 0x08,
    .x5007_interruptLowToHigh8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5008_interruptHighToLow8Bit_sub0 = 0x08,
    .x5008_interruptHighToLow8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5100_readValue8bit_sub0 = 0x08,
    .x5100_readValue8bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5101_inputOff8bit_sub0 = 0x08,
    .x5101_inputOff8bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5102_inputOn8bit_sub0 = 0x08,
    .x5102_inputOn8bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5103_inputSwitch8bit_sub0 = 0x08,
    .x5103_inputSwitch8bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5201_writeOffOutput8Bit_sub0 = 0x08,
    .x5201_writeOffOutput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5202_writeOnOutput8Bit_sub0 = 0x08,
    .x5202_writeOnOutput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x5203_writeSwitchOutput8Bit_sub0 = 0x08,
    .x5203_writeSwitchOutput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6000_readInput8Bit_sub0 = 0x08,
    .x6000_readInput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6100_readValue16Bit_sub0 = 0x04,
    .x6100_readValue16Bit = {0x0000, 0x0000, 0x0000, 0x0000},
    .x6200_writeOutput8Bit_sub0 = 0x08,
    .x6200_writeOutput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6206_errorModeOutput8Bit_sub0 = 0x08,
    .x6206_errorModeOutput8Bit = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF},
    .x6207_errorValueOutput8Bit_sub0 = 0x08,
    .x6207_errorValueOutput8Bit = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6401_readAnalogueInput16Bit_sub0 = 0x10,
    .x6401_readAnalogueInput16Bit = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6402_readAnalogueInput32Bit_sub0 = 0x04,
    .x6402_readAnalogueInput32Bit = {0, 0, 0, 0},
    .x6411_writeAnalogueOutput16Bit_sub0 = 0x04,
    .x6411_writeAnalogueOutput16Bit = {0, 0, 0, 0},
    .x6444_analogueOutputErrorValueInteger_sub0 = 0x08,
    .x6444_analogueOutputErrorValueInteger = {0, 0, 0, 0, 0, 0, 0, 0},
    .xA040_userObjectA040_sub0 = 0x08,
    .xA040_userObjectA040 = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .xA4C0_userObjectA4C0_sub0 = 0x08,
    .xA4C0_userObjectA4C0 = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
};

OD_ATTR_EEPROM OD_EEPROM_t OD_EEPROM = {
    .x2000_userEEPROM_sub0 = 0x08,
    .x2000_userEEPROM = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1404_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1405_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1406_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1604_RPDOMappingParameter[9];
    OD_obj_record_t o_1605_RPDOMappingParameter[9];
    OD_obj_record_t o_1606_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_record_t o_1A01_TPDOMappingParameter[9];
    OD_obj_record_t o_1A02_TPDOMappingParameter[9];
    OD_obj_record_t o_1A03_TPDOMappingParameter[9];
    OD_obj_array_t o_2000_userEEPROM;
    OD_obj_var_t o_2101_nodeID;
    OD_obj_var_t o_2102_bitrate;
    OD_obj_var_t o_2200_domainUpload;
    OD_obj_array_t o_2300_schedulerActivates;
    OD_obj_array_t o_2301_schedulerOutputValue;
    OD_obj_array_t o_2302_schedulerOutputAddress;
    OD_obj_array_t o_2303_schedulerTime;
    OD_obj_array_t o_2304_schedulerTimeHour;
    OD_obj_array_t o_2305_schedulerTimeMinute;
    OD_obj_array_t o_4002_debounceFilterMask8Bit;
    OD_obj_var_t o_4003_debounceTime;
    OD_obj_array_t o_4004_AC_FilterMask8Bit;
    OD_obj_var_t o_4005_AC_Time;
    OD_obj_array_t o_4201_outputPeriod;
    OD_obj_array_t o_4203_outputImpulseTime;
    OD_obj_array_t o_4401_processAnalogueInput;
    OD_obj_array_t o_4402_multiplierAnalogueInput;
    OD_obj_array_t o_4403_dividerAnalogueInput;
    OD_obj_var_t o_4500_LCD;
    OD_obj_array_t o_4501_WM_Setting;
    OD_obj_array_t o_4502_WM_AngleStart;
    OD_obj_array_t o_4503_WM_AngleStop;
    OD_obj_array_t o_4504_WM_Speed;
    OD_obj_array_t o_4510_userSettings;
    OD_obj_array_t o_5000_interrupt8bit;
    OD_obj_array_t o_5006_interruptAnyChange8Bitt;
    OD_obj_array_t o_5007_interruptLowToHigh8Bit;
    OD_obj_array_t o_5008_interruptHighToLow8Bit;
    OD_obj_array_t o_5100_readValue8bit;
    OD_obj_array_t o_5101_inputOff8bit;
    OD_obj_array_t o_5102_inputOn8bit;
    OD_obj_array_t o_5103_inputSwitch8bit;
    OD_obj_array_t o_5201_writeOffOutput8Bit;
    OD_obj_array_t o_5202_writeOnOutput8Bit;
    OD_obj_array_t o_5203_writeSwitchOutput8Bit;
    OD_obj_array_t o_5204_outputDuty;
    OD_obj_array_t o_5205_outputImpilse;
    OD_obj_array_t o_5301_outputMask;
    OD_obj_array_t o_5302_inputRegisterAddresses;
    OD_obj_array_t o_5303_inputValueMasks;
    OD_obj_array_t o_5304_inputValuePolarity;
    OD_obj_array_t o_5401_inputRegisterAddresses;
    OD_obj_array_t o_5402_inputRegisterMasks;
    OD_obj_array_t o_5403_inputRegisterPolarity;
    OD_obj_array_t o_5404_outputRegisterAddresses;
    OD_obj_array_t o_5405_outputValues;
    OD_obj_array_t o_5406_ruleMode;
    OD_obj_array_t o_6000_readInput8Bit;
    OD_obj_array_t o_6002_polarityInput8Bit;
    OD_obj_array_t o_6003_filterConstantInput8Bit;
    OD_obj_var_t o_6005_globalInterruptEnable;
    OD_obj_array_t o_6006_interruptMaskAnyChange8Bit;
    OD_obj_array_t o_6007_interruptMaskLowToHigh8Bit;
    OD_obj_array_t o_6008_interruptMaskHighToLow8Bit;
    OD_obj_array_t o_6100_readValue16Bit;
    OD_obj_array_t o_6200_writeOutput8Bit;
    OD_obj_array_t o_6202_polarityOutput8Bit;
    OD_obj_array_t o_6206_errorModeOutput8Bit;
    OD_obj_array_t o_6207_errorValueOutput8Bit;
    OD_obj_array_t o_6208_filterMaskOutput8Bit;
    OD_obj_array_t o_6401_readAnalogueInput16Bit;
    OD_obj_array_t o_6402_readAnalogueInput32Bit;
    OD_obj_array_t o_6411_writeAnalogueOutput16Bit;
    OD_obj_array_t o_6421_interruptTriggerSelection;
    OD_obj_var_t o_6423_analogInputGlobalInterruptEnable;
    OD_obj_array_t o_6424_analogInputUpperLimit;
    OD_obj_array_t o_6425_analogInputLowerLimit;
    OD_obj_array_t o_6426_analogInputDelta;
    OD_obj_array_t o_6427_analogInputDeltaNegative;
    OD_obj_array_t o_6428_analogInputDeltaPositive;
    OD_obj_array_t o_6429_analogInputTriggers;
    OD_obj_array_t o_6431_analogInputCompensate;
    OD_obj_array_t o_6443_analogueOutputErrorMode;
    OD_obj_array_t o_6444_analogueOutputErrorValueInteger;
    OD_obj_array_t o_A040_userObjectA040;
    OD_obj_array_t o_A4C0_userObjectA4C0;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_PERSIST_COMM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 15
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 15
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1404_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1404_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1404_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1404_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1404_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1405_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1405_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1405_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1405_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1405_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1406_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1406_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1406_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1406_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1406_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1604_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1604_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1605_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1605_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1606_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1606_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2000_userEEPROM = {
        .dataOrig0 = &OD_EEPROM.x2000_userEEPROM_sub0,
        .dataOrig = &OD_EEPROM.x2000_userEEPROM[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2101_nodeID = {
        .dataOrig = &OD_PERSIST_COMM.x2101_nodeID,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_2102_bitrate = {
        .dataOrig = &OD_PERSIST_COMM.x2102_bitrate,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_2200_domainUpload = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 0
    },
    .o_2300_schedulerActivates = {
        .dataOrig0 = &OD_PERSIST_COMM.x2300_schedulerActivates_sub0,
        .dataOrig = &OD_PERSIST_COMM.x2300_schedulerActivates[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2301_schedulerOutputValue = {
        .dataOrig0 = &OD_PERSIST_COMM.x2301_schedulerOutputValue_sub0,
        .dataOrig = &OD_PERSIST_COMM.x2301_schedulerOutputValue[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2302_schedulerOutputAddress = {
        .dataOrig0 = &OD_PERSIST_COMM.x2302_schedulerOutputAddress_sub0,
        .dataOrig = &OD_PERSIST_COMM.x2302_schedulerOutputAddress[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2303_schedulerTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x2303_schedulerTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x2303_schedulerTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2304_schedulerTimeHour = {
        .dataOrig0 = &OD_PERSIST_COMM.x2304_schedulerTimeHour_sub0,
        .dataOrig = &OD_PERSIST_COMM.x2304_schedulerTimeHour[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2305_schedulerTimeMinute = {
        .dataOrig0 = &OD_PERSIST_COMM.x2305_schedulerTimeMinute_sub0,
        .dataOrig = &OD_PERSIST_COMM.x2305_schedulerTimeMinute[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_4002_debounceFilterMask8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x4002_debounceFilterMask8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4002_debounceFilterMask8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_4003_debounceTime = {
        .dataOrig = &OD_PERSIST_COMM.x4003_debounceTime,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_4004_AC_FilterMask8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x4004_AC_FilterMask8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4004_AC_FilterMask8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_4005_AC_Time = {
        .dataOrig = &OD_PERSIST_COMM.x4005_AC_Time,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_4201_outputPeriod = {
        .dataOrig0 = &OD_PERSIST_COMM.x4201_outputPeriod_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4201_outputPeriod[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_4203_outputImpulseTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x4203_outputImpulseTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4203_outputImpulseTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_4401_processAnalogueInput = {
        .dataOrig0 = &OD_PERSIST_COMM.x4401_processAnalogueInput_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4401_processAnalogueInput[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_4402_multiplierAnalogueInput = {
        .dataOrig0 = &OD_PERSIST_COMM.x4402_multiplierAnalogueInput_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4402_multiplierAnalogueInput[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_4403_dividerAnalogueInput = {
        .dataOrig0 = &OD_PERSIST_COMM.x4403_dividerAnalogueInput_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4403_dividerAnalogueInput[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_4500_LCD = {
        .dataOrig = &OD_RAM.x4500_LCD,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_4501_WM_Setting = {
        .dataOrig0 = &OD_PERSIST_COMM.x4501_WM_Setting_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4501_WM_Setting[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_4502_WM_AngleStart = {
        .dataOrig0 = &OD_PERSIST_COMM.x4502_WM_AngleStart_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4502_WM_AngleStart[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_4503_WM_AngleStop = {
        .dataOrig0 = &OD_PERSIST_COMM.x4503_WM_AngleStop_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4503_WM_AngleStop[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_4504_WM_Speed = {
        .dataOrig0 = &OD_PERSIST_COMM.x4504_WM_Speed_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4504_WM_Speed[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_4510_userSettings = {
        .dataOrig0 = &OD_PERSIST_COMM.x4510_userSettings_sub0,
        .dataOrig = &OD_PERSIST_COMM.x4510_userSettings[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5000_interrupt8bit = {
        .dataOrig0 = &OD_RAM.x5000_interrupt8bit_sub0,
        .dataOrig = &OD_RAM.x5000_interrupt8bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5006_interruptAnyChange8Bitt = {
        .dataOrig0 = &OD_RAM.x5006_interruptAnyChange8Bitt_sub0,
        .dataOrig = &OD_RAM.x5006_interruptAnyChange8Bitt[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5007_interruptLowToHigh8Bit = {
        .dataOrig0 = &OD_RAM.x5007_interruptLowToHigh8Bit_sub0,
        .dataOrig = &OD_RAM.x5007_interruptLowToHigh8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5008_interruptHighToLow8Bit = {
        .dataOrig0 = &OD_RAM.x5008_interruptHighToLow8Bit_sub0,
        .dataOrig = &OD_RAM.x5008_interruptHighToLow8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5100_readValue8bit = {
        .dataOrig0 = &OD_RAM.x5100_readValue8bit_sub0,
        .dataOrig = &OD_RAM.x5100_readValue8bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5101_inputOff8bit = {
        .dataOrig0 = &OD_RAM.x5101_inputOff8bit_sub0,
        .dataOrig = &OD_RAM.x5101_inputOff8bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5102_inputOn8bit = {
        .dataOrig0 = &OD_RAM.x5102_inputOn8bit_sub0,
        .dataOrig = &OD_RAM.x5102_inputOn8bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5103_inputSwitch8bit = {
        .dataOrig0 = &OD_RAM.x5103_inputSwitch8bit_sub0,
        .dataOrig = &OD_RAM.x5103_inputSwitch8bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5201_writeOffOutput8Bit = {
        .dataOrig0 = &OD_RAM.x5201_writeOffOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x5201_writeOffOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5202_writeOnOutput8Bit = {
        .dataOrig0 = &OD_RAM.x5202_writeOnOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x5202_writeOnOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5203_writeSwitchOutput8Bit = {
        .dataOrig0 = &OD_RAM.x5203_writeSwitchOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x5203_writeSwitchOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5204_outputDuty = {
        .dataOrig0 = &OD_PERSIST_COMM.x5204_outputDuty_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5204_outputDuty[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5205_outputImpilse = {
        .dataOrig0 = &OD_PERSIST_COMM.x5205_outputImpilse_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5205_outputImpilse[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_5301_outputMask = {
        .dataOrig0 = &OD_PERSIST_COMM.x5301_outputMask_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5301_outputMask[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5302_inputRegisterAddresses = {
        .dataOrig0 = &OD_PERSIST_COMM.x5302_inputRegisterAddresses_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5302_inputRegisterAddresses[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5303_inputValueMasks = {
        .dataOrig0 = &OD_PERSIST_COMM.x5303_inputValueMasks_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5303_inputValueMasks[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5304_inputValuePolarity = {
        .dataOrig0 = &OD_PERSIST_COMM.x5304_inputValuePolarity_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5304_inputValuePolarity[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5401_inputRegisterAddresses = {
        .dataOrig0 = &OD_PERSIST_COMM.x5401_inputRegisterAddresses_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5401_inputRegisterAddresses[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5402_inputRegisterMasks = {
        .dataOrig0 = &OD_PERSIST_COMM.x5402_inputRegisterMasks_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5402_inputRegisterMasks[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5403_inputRegisterPolarity = {
        .dataOrig0 = &OD_PERSIST_COMM.x5403_inputRegisterPolarity_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5403_inputRegisterPolarity[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5404_outputRegisterAddresses = {
        .dataOrig0 = &OD_PERSIST_COMM.x5404_outputRegisterAddresses_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5404_outputRegisterAddresses[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5405_outputValues = {
        .dataOrig0 = &OD_PERSIST_COMM.x5405_outputValues_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5405_outputValues[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_5406_ruleMode = {
        .dataOrig0 = &OD_PERSIST_COMM.x5406_ruleMode_sub0,
        .dataOrig = &OD_PERSIST_COMM.x5406_ruleMode[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6000_readInput8Bit = {
        .dataOrig0 = &OD_RAM.x6000_readInput8Bit_sub0,
        .dataOrig = &OD_RAM.x6000_readInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_TSRDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6002_polarityInput8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6002_polarityInput8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6002_polarityInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6003_filterConstantInput8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6003_filterConstantInput8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6003_filterConstantInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6005_globalInterruptEnable = {
        .dataOrig = &OD_PERSIST_COMM.x6005_globalInterruptEnable,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6006_interruptMaskAnyChange8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6006_interruptMaskAnyChange8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6006_interruptMaskAnyChange8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6007_interruptMaskLowToHigh8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6007_interruptMaskLowToHigh8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6007_interruptMaskLowToHigh8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6008_interruptMaskHighToLow8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6008_interruptMaskHighToLow8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6008_interruptMaskHighToLow8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6100_readValue16Bit = {
        .dataOrig0 = &OD_RAM.x6100_readValue16Bit_sub0,
        .dataOrig = &OD_RAM.x6100_readValue16Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_TSRDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6200_writeOutput8Bit = {
        .dataOrig0 = &OD_RAM.x6200_writeOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x6200_writeOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_TSRDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6202_polarityOutput8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6202_polarityOutput8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6202_polarityOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6206_errorModeOutput8Bit = {
        .dataOrig0 = &OD_RAM.x6206_errorModeOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x6206_errorModeOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6207_errorValueOutput8Bit = {
        .dataOrig0 = &OD_RAM.x6207_errorValueOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x6207_errorValueOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6208_filterMaskOutput8Bit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6208_filterMaskOutput8Bit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6208_filterMaskOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6401_readAnalogueInput16Bit = {
        .dataOrig0 = &OD_RAM.x6401_readAnalogueInput16Bit_sub0,
        .dataOrig = &OD_RAM.x6401_readAnalogueInput16Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6402_readAnalogueInput32Bit = {
        .dataOrig0 = &OD_RAM.x6402_readAnalogueInput32Bit_sub0,
        .dataOrig = &OD_RAM.x6402_readAnalogueInput32Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6411_writeAnalogueOutput16Bit = {
        .dataOrig0 = &OD_RAM.x6411_writeAnalogueOutput16Bit_sub0,
        .dataOrig = &OD_RAM.x6411_writeAnalogueOutput16Bit[0],
        .attribute0 = ODA_SDO_RW | ODA_TRPDO | ODA_TSRDO,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_TSRDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6421_interruptTriggerSelection = {
        .dataOrig0 = &OD_PERSIST_COMM.x6421_interruptTriggerSelection_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6421_interruptTriggerSelection[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6423_analogInputGlobalInterruptEnable = {
        .dataOrig = &OD_PERSIST_COMM.x6423_analogInputGlobalInterruptEnable,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6424_analogInputUpperLimit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6424_analogInputUpperLimit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6424_analogInputUpperLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6425_analogInputLowerLimit = {
        .dataOrig0 = &OD_PERSIST_COMM.x6425_analogInputLowerLimit_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6425_analogInputLowerLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6426_analogInputDelta = {
        .dataOrig0 = &OD_PERSIST_COMM.x6426_analogInputDelta_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6426_analogInputDelta[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6427_analogInputDeltaNegative = {
        .dataOrig0 = &OD_PERSIST_COMM.x6427_analogInputDeltaNegative_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6427_analogInputDeltaNegative[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6428_analogInputDeltaPositive = {
        .dataOrig0 = &OD_PERSIST_COMM.x6428_analogInputDeltaPositive_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6428_analogInputDeltaPositive[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6429_analogInputTriggers = {
        .dataOrig0 = &OD_PERSIST_COMM.x6429_analogInputTriggers_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6429_analogInputTriggers[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6431_analogInputCompensate = {
        .dataOrig0 = &OD_PERSIST_COMM.x6431_analogInputCompensate_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6431_analogInputCompensate[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6443_analogueOutputErrorMode = {
        .dataOrig0 = &OD_PERSIST_COMM.x6443_analogueOutputErrorMode_sub0,
        .dataOrig = &OD_PERSIST_COMM.x6443_analogueOutputErrorMode[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6444_analogueOutputErrorValueInteger = {
        .dataOrig0 = &OD_RAM.x6444_analogueOutputErrorValueInteger_sub0,
        .dataOrig = &OD_RAM.x6444_analogueOutputErrorValueInteger[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_A040_userObjectA040 = {
        .dataOrig0 = &OD_RAM.xA040_userObjectA040_sub0,
        .dataOrig = &OD_RAM.xA040_userObjectA040[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_A4C0_userObjectA4C0 = {
        .dataOrig0 = &OD_RAM.xA4C0_userObjectA4C0_sub0,
        .dataOrig = &OD_RAM.xA4C0_userObjectA4C0[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1404, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter, NULL},
    {0x1405, 0x04, ODT_REC, &ODObjs.o_1405_RPDOCommunicationParameter, NULL},
    {0x1406, 0x04, ODT_REC, &ODObjs.o_1406_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1604, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter, NULL},
    {0x1605, 0x09, ODT_REC, &ODObjs.o_1605_RPDOMappingParameter, NULL},
    {0x1606, 0x09, ODT_REC, &ODObjs.o_1606_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x09, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x09, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x2000, 0x09, ODT_ARR, &ODObjs.o_2000_userEEPROM, NULL},
    {0x2101, 0x01, ODT_VAR, &ODObjs.o_2101_nodeID, NULL},
    {0x2102, 0x01, ODT_VAR, &ODObjs.o_2102_bitrate, NULL},
    {0x2200, 0x01, ODT_VAR, &ODObjs.o_2200_domainUpload, NULL},
    {0x2300, 0x09, ODT_ARR, &ODObjs.o_2300_schedulerActivates, NULL},
    {0x2301, 0x09, ODT_ARR, &ODObjs.o_2301_schedulerOutputValue, NULL},
    {0x2302, 0x09, ODT_ARR, &ODObjs.o_2302_schedulerOutputAddress, NULL},
    {0x2303, 0x09, ODT_ARR, &ODObjs.o_2303_schedulerTime, NULL},
    {0x2304, 0x09, ODT_ARR, &ODObjs.o_2304_schedulerTimeHour, NULL},
    {0x2305, 0x09, ODT_ARR, &ODObjs.o_2305_schedulerTimeMinute, NULL},
    {0x4002, 0x09, ODT_ARR, &ODObjs.o_4002_debounceFilterMask8Bit, NULL},
    {0x4003, 0x01, ODT_VAR, &ODObjs.o_4003_debounceTime, NULL},
    {0x4004, 0x09, ODT_ARR, &ODObjs.o_4004_AC_FilterMask8Bit, NULL},
    {0x4005, 0x01, ODT_VAR, &ODObjs.o_4005_AC_Time, NULL},
    {0x4201, 0x09, ODT_ARR, &ODObjs.o_4201_outputPeriod, NULL},
    {0x4203, 0x09, ODT_ARR, &ODObjs.o_4203_outputImpulseTime, NULL},
    {0x4401, 0x11, ODT_ARR, &ODObjs.o_4401_processAnalogueInput, NULL},
    {0x4402, 0x11, ODT_ARR, &ODObjs.o_4402_multiplierAnalogueInput, NULL},
    {0x4403, 0x11, ODT_ARR, &ODObjs.o_4403_dividerAnalogueInput, NULL},
    {0x4500, 0x01, ODT_VAR, &ODObjs.o_4500_LCD, NULL},
    {0x4501, 0x05, ODT_ARR, &ODObjs.o_4501_WM_Setting, NULL},
    {0x4502, 0x11, ODT_ARR, &ODObjs.o_4502_WM_AngleStart, NULL},
    {0x4503, 0x11, ODT_ARR, &ODObjs.o_4503_WM_AngleStop, NULL},
    {0x4504, 0x11, ODT_ARR, &ODObjs.o_4504_WM_Speed, NULL},
    {0x4510, 0x11, ODT_ARR, &ODObjs.o_4510_userSettings, NULL},
    {0x5000, 0x09, ODT_ARR, &ODObjs.o_5000_interrupt8bit, NULL},
    {0x5006, 0x09, ODT_ARR, &ODObjs.o_5006_interruptAnyChange8Bitt, NULL},
    {0x5007, 0x09, ODT_ARR, &ODObjs.o_5007_interruptLowToHigh8Bit, NULL},
    {0x5008, 0x09, ODT_ARR, &ODObjs.o_5008_interruptHighToLow8Bit, NULL},
    {0x5100, 0x09, ODT_ARR, &ODObjs.o_5100_readValue8bit, NULL},
    {0x5101, 0x09, ODT_ARR, &ODObjs.o_5101_inputOff8bit, NULL},
    {0x5102, 0x09, ODT_ARR, &ODObjs.o_5102_inputOn8bit, NULL},
    {0x5103, 0x09, ODT_ARR, &ODObjs.o_5103_inputSwitch8bit, NULL},
    {0x5201, 0x09, ODT_ARR, &ODObjs.o_5201_writeOffOutput8Bit, NULL},
    {0x5202, 0x09, ODT_ARR, &ODObjs.o_5202_writeOnOutput8Bit, NULL},
    {0x5203, 0x09, ODT_ARR, &ODObjs.o_5203_writeSwitchOutput8Bit, NULL},
    {0x5204, 0x09, ODT_ARR, &ODObjs.o_5204_outputDuty, NULL},
    {0x5205, 0x09, ODT_ARR, &ODObjs.o_5205_outputImpilse, NULL},
    {0x5301, 0x09, ODT_ARR, &ODObjs.o_5301_outputMask, NULL},
    {0x5302, 0x09, ODT_ARR, &ODObjs.o_5302_inputRegisterAddresses, NULL},
    {0x5303, 0x09, ODT_ARR, &ODObjs.o_5303_inputValueMasks, NULL},
    {0x5304, 0x09, ODT_ARR, &ODObjs.o_5304_inputValuePolarity, NULL},
    {0x5401, 0x19, ODT_ARR, &ODObjs.o_5401_inputRegisterAddresses, NULL},
    {0x5402, 0x19, ODT_ARR, &ODObjs.o_5402_inputRegisterMasks, NULL},
    {0x5403, 0x19, ODT_ARR, &ODObjs.o_5403_inputRegisterPolarity, NULL},
    {0x5404, 0x19, ODT_ARR, &ODObjs.o_5404_outputRegisterAddresses, NULL},
    {0x5405, 0x19, ODT_ARR, &ODObjs.o_5405_outputValues, NULL},
    {0x5406, 0x19, ODT_ARR, &ODObjs.o_5406_ruleMode, NULL},
    {0x6000, 0x09, ODT_ARR, &ODObjs.o_6000_readInput8Bit, NULL},
    {0x6002, 0x09, ODT_ARR, &ODObjs.o_6002_polarityInput8Bit, NULL},
    {0x6003, 0x09, ODT_ARR, &ODObjs.o_6003_filterConstantInput8Bit, NULL},
    {0x6005, 0x01, ODT_VAR, &ODObjs.o_6005_globalInterruptEnable, NULL},
    {0x6006, 0x09, ODT_ARR, &ODObjs.o_6006_interruptMaskAnyChange8Bit, NULL},
    {0x6007, 0x09, ODT_ARR, &ODObjs.o_6007_interruptMaskLowToHigh8Bit, NULL},
    {0x6008, 0x09, ODT_ARR, &ODObjs.o_6008_interruptMaskHighToLow8Bit, NULL},
    {0x6100, 0x05, ODT_ARR, &ODObjs.o_6100_readValue16Bit, NULL},
    {0x6200, 0x09, ODT_ARR, &ODObjs.o_6200_writeOutput8Bit, NULL},
    {0x6202, 0x09, ODT_ARR, &ODObjs.o_6202_polarityOutput8Bit, NULL},
    {0x6206, 0x09, ODT_ARR, &ODObjs.o_6206_errorModeOutput8Bit, NULL},
    {0x6207, 0x09, ODT_ARR, &ODObjs.o_6207_errorValueOutput8Bit, NULL},
    {0x6208, 0x09, ODT_ARR, &ODObjs.o_6208_filterMaskOutput8Bit, NULL},
    {0x6401, 0x11, ODT_ARR, &ODObjs.o_6401_readAnalogueInput16Bit, NULL},
    {0x6402, 0x05, ODT_ARR, &ODObjs.o_6402_readAnalogueInput32Bit, NULL},
    {0x6411, 0x05, ODT_ARR, &ODObjs.o_6411_writeAnalogueOutput16Bit, NULL},
    {0x6421, 0x09, ODT_ARR, &ODObjs.o_6421_interruptTriggerSelection, NULL},
    {0x6423, 0x01, ODT_VAR, &ODObjs.o_6423_analogInputGlobalInterruptEnable, NULL},
    {0x6424, 0x11, ODT_ARR, &ODObjs.o_6424_analogInputUpperLimit, NULL},
    {0x6425, 0x11, ODT_ARR, &ODObjs.o_6425_analogInputLowerLimit, NULL},
    {0x6426, 0x11, ODT_ARR, &ODObjs.o_6426_analogInputDelta, NULL},
    {0x6427, 0x11, ODT_ARR, &ODObjs.o_6427_analogInputDeltaNegative, NULL},
    {0x6428, 0x11, ODT_ARR, &ODObjs.o_6428_analogInputDeltaPositive, NULL},
    {0x6429, 0x05, ODT_ARR, &ODObjs.o_6429_analogInputTriggers, NULL},
    {0x6431, 0x11, ODT_ARR, &ODObjs.o_6431_analogInputCompensate, NULL},
    {0x6443, 0x09, ODT_ARR, &ODObjs.o_6443_analogueOutputErrorMode, NULL},
    {0x6444, 0x09, ODT_ARR, &ODObjs.o_6444_analogueOutputErrorValueInteger, NULL},
    {0xA040, 0x09, ODT_ARR, &ODObjs.o_A040_userObjectA040, NULL},
    {0xA4C0, 0x09, ODT_ARR, &ODObjs.o_A4C0_userObjectA4C0, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
